### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_MAG3110_Breakout_Board_Arduino_Library#5]
In the file "src/SparkFun_MAG3110.cpp", in the function "readMag()" there is waiting after the Wire.requestFrom(). This line: `while( Wire.available() != 6 ) {}` may be removed, it is at the moment at line 93.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by bboyho** [comment]
Hi,

Thank you for the feedback. I have removed the line. =)
